export const actionTypes = {
    SET_SELLER_PRODUCTS : 'FETCH_ALL_SELLER_PRODUCTS',
    ADD_SELLER_PRODUCT : 'ADD_SELLER_PRODUCT',
    EDIT_SELLER_PRODUCT : 'EDIT_SELLER_PRODUCT',
    DELETE_SELLER_PRODUCT : 'DELETE_SELLER_PRODUCT',
    SET_LOADING : 'SET_LOADING'
} 